---
- name: Add key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name:  Repo postgres
  copy:
    dest: /etc/apt/sources.list.d/postgresql.list
    content: deb [arch=amd64] http://apt.postgresql.org/pub/repos/apt/ jammy-pgdg main

- name: Run apt upgrade
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 432000

- name: Install acl packages to start postgresql unpriv user
  apt:
    package: acl
    state: latest

- name: Install packages
  apt:
    package: "{{ item  }}-{{ postgresql_version }}"
    state: latest
  with_items:
    - postgresql

- name: Check if PostgreSQL is initialized
  ansible.builtin.stat:
    path: "{{ postgresql_data_dir }}/pg_hba.conf"
  register: postgres_data

- name: Empty data dir
  ansible.builtin.file:
    path: "{{ postgresql_data_dir }}"
    state: absent
  when: not postgres_data.stat.exists

- name: Initialize PostgreSQL
  ansible.builtin.shell: "{{ postgresql_bin_path }}/initdb -D {{ postgresql_data_dir }}"
  become: true
  become_user: postgres
  when: not postgres_data.stat.exists

- name: Start and enable service
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: true