all:
  children:
    app:
      hosts:
        vm2:
          ansible_host: 192.168.10.15
          ansible_ssh_user: user
        vm3:
          ansible_host: 192.168.10.10
          ansible_ssh_user: user
    database:
      hosts:
        vm1:
          ansible_host: 192.168.10.14
          ansible_ssh_user: user
      vars:
        postgresql_version: "12"
        postgresql_bin_path: "/usr/lib/postgresql/{{ postgresql_version }}/bin"
        postgresql_data_dir: "/var/lib/postgresql/{{ postgresql_version }}/main"
    web:
      hosts:
        vm1:
          ansible_host: 192.168.10.14
          ansible_ssh_user: user